# Generated by Django 4.2 on 2024-01-02 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appSerial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='registroSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoRegistro', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='datoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valorDato', models.CharField(blank=True, max_length=32, null=True)),
                ('registroDato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appSerial.registrosistema')),
            ],
        ),
    ]
